import { createPlaceFallbackImage } from '../../../utils/placeArtwork';
import type {
  DestinationDefinition,
  DestinationSupportData,
  DestinationTextContent,
} from './types';

const buildHeroImage = (name: string, city: string, category: string) =>
  createPlaceFallbackImage({ name, city, category });

const buildSupportFallback = (destinationName: string, focus: string): DestinationSupportData => ({
  stays: [
    {
      title: `${destinationName} base stay`,
      description: `A practical accommodation profile for travelers using ${destinationName} as the main anchor of their trip.`,
      meta: 'Good for independent and guided visitors',
      tags: ['Stay', 'Flexible', 'Regional base'],
    },
    {
      title: `${destinationName} route lodge`,
      description: `A lighter stay concept suited for travelers combining nearby points and regional day routes.`,
      meta: 'Useful for day-plan extensions',
      tags: ['Overnight', 'Route-ready', 'Travel support'],
    },
  ],
  guides: [
    {
      title: `${destinationName} local guide`,
      description: `A guide profile focused on helping visitors understand ${destinationName} with stronger local context.`,
      meta: `Focus: ${focus}`,
      tags: ['Local knowledge', 'Flexible', 'Storytelling'],
    },
    {
      title: `${destinationName} route companion`,
      description: 'Useful for logistics, sequencing stops, and making the overall destination visit feel easier to follow.',
      meta: 'Best for first-time visitors',
      tags: ['Planning help', 'Navigation', 'Support'],
    },
  ],
  food: [
    {
      title: `${destinationName} lunch stop`,
      description: 'A practical food card that helps the route feel realistic instead of purely inspirational.',
      meta: 'Fits between major stops',
      tags: ['Food', 'Break', 'Local taste'],
    },
    {
      title: `${destinationName} market table`,
      description: 'A lighter local-food option for travelers who want a short, authentic pause during the route.',
      meta: 'Short-stop format',
      tags: ['Market', 'Tea', 'Snacks'],
    },
  ],
  tours: [
    {
      title: `${destinationName} highlights route`,
      description: 'A guided outline that combines the most visible points into one clean destination plan.',
      meta: 'Half day to full day',
      tags: ['Guided', 'Highlights', 'Structured'],
    },
    {
      title: `${destinationName} themed itinerary`,
      description: `A focused route concept built around ${focus.toLowerCase()} for travelers who want clarity instead of too many options.`,
      meta: 'Good for demo-ready planning',
      tags: ['Thematic', 'Tourism-ready', 'Flexible'],
    },
  ],
});

export const destinationCatalog: DestinationDefinition[] = [
  {
    slug: 'nukus',
    city: 'Nukus',
    region: 'Republic of Karakalpakstan',
    category: 'culture',
    cities: ['Nukus'],
    heroCategory: 'museum',
    heroImage: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQTV-N3g12TWB7MPWhK-LiAvF8_JRP186EZhQ&s',
    tags: ['Museums', 'City break', 'Culture'],
    estimatedVisitMinutes: 480,
    bestSeason: 'Spring and autumn',
    coordinates: { lat: 42.4602, lng: 59.6166 },
    nearbyPoints: [
      {
        id: 'savitsky-museum',
        title: 'Savitsky Museum quarter',
        description: 'The strongest cultural anchor in Nukus for art-led discovery and guided storytelling.',
        category: 'museum',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQTV-N3g12TWB7MPWhK-LiAvF8_JRP186EZhQ&s',
        coordinates: { lat: 42.4662, lng: 59.6106 },
        estimatedVisitMinutes: 120,
        tags: ['Art', 'Collections'],
      },
      {
        id: 'berdakh-theater',
        title: 'Berdakh theater and civic center',
        description: 'A practical city stop that adds local cultural context around the main museums and institutions.',
        category: 'culture',
        coordinates: { lat: 42.4725, lng: 59.6029 },
        estimatedVisitMinutes: 60,
        tags: ['Architecture', 'City life'],
      },
      {
        id: 'nukus-bazaar',
        title: 'Central bazaar stop',
        description: 'Useful for local food, short breaks, and seeing everyday city rhythms between formal attractions.',
        category: 'food',
        coordinates: { lat: 42.4582, lng: 59.6088 },
        estimatedVisitMinutes: 45,
        tags: ['Local food', 'Market'],
      },
    ],
  },
  {
    slug: 'moynaq',
    city: 'Moynaq',
    region: 'Northern Karakalpakstan',
    category: 'history',
    cities: ['Moynaq'],
    heroCategory: 'history',
    heroImage: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQQR_-yfH0WBYHohfAlBI6mEvp-LjEUo3jAoA&s',
    tags: ['Aral Sea', 'History', 'Photography'],
    estimatedVisitMinutes: 360,
    bestSeason: 'Spring and early autumn',
    coordinates: { lat: 43.7683, lng: 59.0214 },
    nearbyPoints: [
      {
        id: 'ship-cemetery',
        title: 'Ship cemetery ridge',
        description: 'The most recognizable stop in Moynaq and the emotional center of the Aral Sea story.',
        category: 'history',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQQR_-yfH0WBYHohfAlBI6mEvp-LjEUo3jAoA&s',
        coordinates: { lat: 43.7689, lng: 59.0102 },
        estimatedVisitMinutes: 90,
        tags: ['Aral Sea', 'Photography'],
      },
      {
        id: 'moynaq-museum',
        title: 'Moynaq museum stop',
        description: 'Adds historical and environmental context before or after visiting the shoreline remains.',
        category: 'museum',
        coordinates: { lat: 43.7696, lng: 59.0187 },
        estimatedVisitMinutes: 60,
        tags: ['Museum', 'History'],
      },
      {
        id: 'former-port-viewpoint',
        title: 'Former port viewpoint',
        description: 'A simple but powerful viewing point for understanding how the destination changed over time.',
        category: 'nature',
        coordinates: { lat: 43.7727, lng: 59.0144 },
        estimatedVisitMinutes: 40,
        tags: ['Viewpoint', 'Landscape'],
      },
    ],
  },
  {
    slug: 'ellikqala',
    city: 'Ellikqala',
    region: 'Southern fortress zone',
    category: 'adventure',
    cities: ['Ellikqala'],
    heroCategory: 'adventure',
    heroImage: buildHeroImage('Ellikqala fortresses', 'Ellikqala', 'adventure'),
    tags: ['Fortresses', 'Desert route', 'Road trip'],
    estimatedVisitMinutes: 540,
    bestSeason: 'Spring and autumn',
    coordinates: { lat: 42.1104, lng: 61.0334 },
    nearbyPoints: [
      {
        id: 'ayaz-kala',
        title: 'Ayaz Kala fortress cluster',
        description: 'The most cinematic fortress stop, best for panoramic views and a high-impact first visit.',
        category: 'history',
        coordinates: { lat: 42.0112, lng: 61.0279 },
        estimatedVisitMinutes: 120,
        tags: ['Fortress', 'Panorama'],
      },
      {
        id: 'topraq-kala',
        title: 'Topraq Kala ruins',
        description: 'A major archaeological stop that makes the broader Ellikqala route feel richer and more complete.',
        category: 'history',
        coordinates: { lat: 41.9285, lng: 60.8162 },
        estimatedVisitMinutes: 90,
        tags: ['Archaeology', 'Ancient route'],
      },
      {
        id: 'qizil-kala',
        title: 'Qizil Kala stop',
        description: 'A compact add-on point for travelers who want a denser fortress itinerary in one day.',
        category: 'adventure',
        coordinates: { lat: 41.9298, lng: 60.8125 },
        estimatedVisitMinutes: 60,
        tags: ['Road stop', 'History'],
      },
    ],
  },
  {
    slug: 'ustyurt',
    city: 'Ustyurt Plateau',
    region: 'Remote western plateau',
    category: 'nature',
    cities: ['Qonirat', 'Moynaq'],
    heroCategory: 'nature',
    heroImage: buildHeroImage('Ustyurt plateau views', 'Ustyurt', 'nature'),
    tags: ['Remote nature', 'Plateau', 'Expedition'],
    estimatedVisitMinutes: 600,
    bestSeason: 'Late spring and autumn',
    coordinates: { lat: 43.266, lng: 57.916 },
    nearbyPoints: [
      {
        id: 'ustyurt-viewpoint',
        title: 'Plateau edge viewpoint',
        description: 'A wide-angle landscape stop suited for travelers who want scale, silence, and remote scenery.',
        category: 'nature',
        coordinates: { lat: 43.284, lng: 57.934 },
        estimatedVisitMinutes: 45,
        tags: ['Viewpoint', 'Nature'],
      },
      {
        id: 'canyon-approach',
        title: 'Canyon approach road',
        description: 'Useful for off-road travelers planning a route with scenic pauses instead of dense urban stops.',
        category: 'adventure',
        coordinates: { lat: 43.241, lng: 57.882 },
        estimatedVisitMinutes: 60,
        tags: ['Off-road', 'Landscape'],
      },
      {
        id: 'remote-camp-zone',
        title: 'Remote camp zone',
        description: 'A practical overnight-style marker for multi-stop plateau travel and outdoor-focused journeys.',
        category: 'nature',
        coordinates: { lat: 43.228, lng: 57.965 },
        estimatedVisitMinutes: 90,
        tags: ['Camp', 'Night sky'],
      },
    ],
  },
];

export const destinationTextFallbacks: Record<string, DestinationTextContent> = {
  nukus: {
    name: 'Nukus',
    kicker: 'Culture capital',
    summary: 'The strongest city base for museums, culture, food, and first-time regional discovery.',
    overview: 'Nukus gives travelers a reliable starting point with major museums, civic landmarks, and easy access to local services.',
    longDescription: 'For a destination-first tourism product, Nukus works as the most dependable gateway. Visitors can start with major cultural institutions, add food or market stops, and then decide whether to continue into regional routes or remain in the city. It is the most practical destination for museum-led travelers and judges who need to understand the product quickly.',
    bestFor: ['Museums', 'Culture', 'Food'],
    metrics: [
      { label: 'Ideal stay', value: '1-2 days' },
      { label: 'Travel mood', value: 'City discovery' },
      { label: 'Best starting point', value: 'Regional gateway' },
    ],
  },
  moynaq: {
    name: 'Moynaq',
    kicker: 'Aral Sea story',
    summary: "A destination shaped by environmental history, dramatic visuals, and one of the region's clearest travel narratives.",
    overview: 'Moynaq is one of the most memorable destinations in Karakalpakstan for travelers who want strong meaning and strong imagery in the same route.',
    longDescription: 'Moynaq is not just a place to stop for photos. It is a destination where the route, local story, and emotional impact all align. Travelers can combine the ship cemetery, museum context, and nearby viewpoints into a compact but memorable visit. It is particularly strong for history, photography, and first-time visitors who need a clear destination story.',
    bestFor: ['History', 'Photography', 'Aral Sea'],
    metrics: [
      { label: 'Ideal stay', value: 'Half day' },
      { label: 'Travel mood', value: 'Story-led visit' },
      { label: 'Best known for', value: 'Aral Sea history' },
    ],
  },
  ellikqala: {
    name: 'Ellikqala',
    kicker: 'Fortress landscapes',
    summary: 'A road-trip destination built around ancient fortresses, desert scenery, and archaeological scale.',
    overview: 'Ellikqala works best for travelers who want open landscapes, heritage sites, and a more cinematic route structure.',
    longDescription: 'Ellikqala stands out because it offers multiple high-value stops within one destination story. Instead of a single landmark, the traveler gets a chain of fortress points, scenic approaches, and archaeological context. For Baramiz, this makes Ellikqala ideal for showing how destination discovery can naturally extend into map-based route planning.',
    bestFor: ['Fortresses', 'Adventure', 'Road trips'],
    metrics: [
      { label: 'Ideal stay', value: '1 day' },
      { label: 'Travel mood', value: 'Scenic drive' },
      { label: 'Best known for', value: 'Fortress route' },
    ],
  },
  ustyurt: {
    name: 'Ustyurt',
    kicker: 'Plateau horizons',
    summary: 'Remote landscapes and wide horizons for travelers who prioritize nature, scale, and expedition-style movement.',
    overview: 'Ustyurt is a destination for travelers who want a less urban, more open version of Karakalpakstan travel.',
    longDescription: 'Ustyurt should feel different from the rest of the platform: less dense, more atmospheric, and more dependent on route planning. It is the best destination for showing that Baramiz can support both independent travelers and guided journeys. The product value here is not only in the places, but in helping travelers understand sequence, access, and support services.',
    bestFor: ['Nature', 'Expedition', 'Photography'],
    metrics: [
      { label: 'Ideal stay', value: '1 day+' },
      { label: 'Travel mood', value: 'Remote exploration' },
      { label: 'Best known for', value: 'Plateau landscapes' },
    ],
  },
};

export const destinationSupportFallbacks: Record<string, DestinationSupportData> = {
  nukus: buildSupportFallback('Nukus', 'museums and culture'),
  moynaq: buildSupportFallback('Moynaq', 'Aral Sea history'),
  ellikqala: buildSupportFallback('Ellikqala', 'fortresses and road travel'),
  ustyurt: buildSupportFallback('Ustyurt', 'remote landscapes and outdoor movement'),
};

