export const routePaths = {
  root: '/',
  home: '/app/home',
  appSplash: '/app/splash',
  appLanguage: '/app/language',
  appOnboarding: '/app/onboarding',
  appRoot: '/app',
  appHome: '/app/home',
  appExplore: '/app/explore',
  appDestinations: '/app/destinations',
  appDestinationDetails: (slug: string) => `/app/destinations/${slug}`,
  appPlaceDetails: (id: string) => `/app/places/${id}`,
  appServices: '/app/services',
  appGuides: '/app/guides',
  appRouteBuilder: '/app/route-builder',
  appRouteResult: '/app/route-result',
  destinations: '/destinations',
  destinationDetails: (slug: string) => `/destinations/${slug}`,
  places: '/places',
  placeDetails: (id: string) => `/places/${id}`,
  map: '/map',
  services: '/services',
  guides: '/guides',
  routeGenerator: '/route-generator',
  routeResult: '/route-result',
  about: '/about',
  admin: {
    root: '/admin',
    categories: '/admin/categories',
    places: '/admin/places',
    placeCreate: '/admin/places/new',
    placeEdit: (id: string) => `/admin/places/${id}/edit`,
  },
} as const;
