export const routePaths = {
  root: '/',
  home: '/app/home',
  appSplash: '/app/splash',
  appLanguage: '/app/language',
  appOnboarding: '/app/onboarding',
  appAuthRequired: '/app/auth-required',
  appLogin: '/app/login',
  appRegister: '/app/register',
  appRoot: '/app',
  appHome: '/app/home',
  appExplore: '/app/explore',
  appDestinations: '/app/destinations',
  appDestinationDetails: (slug: string) => `/app/destinations/${slug}`,
  appPlaceDetails: (id: string) => `/app/places/${id}`,
  appServices: '/app/services',
  appGuides: '/app/guides',
  appProfile: '/app/profile',
  appTripHotels: '/app/trip-hotels',
  appHotelDetails: (slug: string) => `/app/trip-hotels/${slug}`,
  appRouteBuilder: '/app/route-builder',
  appRouteResult: '/app/route-result',
  appBookingDetails: '/app/booking',
  appBookingReview: '/app/booking/review',
  appPaymentMethods: '/app/booking/payment',
  appBookingConfirmation: '/app/booking/confirmation',
  destinations: '/destinations',
  destinationDetails: (slug: string) => `/destinations/${slug}`,
  places: '/places',
  placeDetails: (id: string) => `/places/${id}`,
  map: '/map',
  services: '/services',
  guides: '/guides',
  hotels: '/hotels',
  hotelDetails: (slug: string) => `/hotels/${slug}`,
  routeGenerator: '/route-generator',
  routeResult: '/route-result',
  about: '/about',
  admin: {
    root: '/admin',
    categories: '/admin/categories',
    places: '/admin/places',
    placeCreate: '/admin/places/new',
    placeEdit: (id: string) => `/admin/places/${id}/edit`,
  },
} as const;
