import type { HotelStay } from './types';

export const hotelCatalog: HotelStay[] = [
  {
    id: 'savitsky-plaza',
    slug: 'savitsky-plaza',
    name: 'Savitsky Plaza Hotel',
    city: 'Nukus',
    region: 'Karakalpakstan',
    location: 'Central Nukus, near Savitsky Museum',
    shortDescription: 'A calm city-base hotel for museum visits, easy transfers, and evening walks.',
    description:
      'Savitsky Plaza is designed as a comfortable city base for travelers exploring Nukus and building multi-stop regional routes. It works well for culture-focused trips that need reliable transfers, quiet rooms, and a polished lobby to reset between stops.',
    priceFrom: 92,
    currency: 'USD',
    rating: 4.8,
    images: [
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80',
    ],
    amenities: ['Breakfast included', 'Airport transfer', 'Quiet work lounge', 'Late check-in'],
    tags: ['Museum access', 'City center', 'Comfort stay'],
    recommendedTripStyles: ['culture', 'balanced'],
    recommendedBudgets: ['comfortable', 'premium'],
    nearbyKeywords: ['savitsky', 'museum', 'nukus'],
  },
  {
    id: 'jipek-joli-boutique',
    slug: 'jipek-joli-boutique',
    name: 'Jipek Joli Boutique Stay',
    city: 'Nukus',
    region: 'Karakalpakstan',
    location: 'Old Nukus district',
    shortDescription: 'A boutique stay with warm interiors and easy access to food and local craft stops.',
    description:
      'Jipek Joli Boutique Stay suits travelers who want a smaller, warmer base with easy access to local food, evening walks, and short intra-city transfers. It fits balanced itineraries and couples looking for a calmer hotel rhythm.',
    priceFrom: 74,
    currency: 'USD',
    rating: 4.6,
    images: [
      'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=80',
    ],
    amenities: ['Breakfast room', 'Family rooms', 'Local host desk', 'Laundry service'],
    tags: ['Boutique', 'Food nearby', 'Warm interiors'],
    recommendedTripStyles: ['balanced', 'family', 'culture'],
    recommendedBudgets: ['light', 'comfortable'],
    nearbyKeywords: ['nukus', 'restaurant', 'craft'],
  },
  {
    id: 'aral-oasis-hotel',
    slug: 'aral-oasis-hotel',
    name: 'Aral Oasis Hotel',
    city: 'Moynaq',
    region: 'Karakalpakstan',
    location: 'Moynaq center, route to Aral viewpoints',
    shortDescription: 'A practical base for Aral Sea trips, with early breakfast and driver-friendly logistics.',
    description:
      'Aral Oasis is built for travelers heading toward Moynaq viewpoints and longer scenic routes. It keeps the stay simple but reliable, with early departures, route lunches, and strong logistics for drivers or regional transfers.',
    priceFrom: 61,
    currency: 'USD',
    rating: 4.4,
    images: [
      'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=80',
    ],
    amenities: ['Early breakfast', 'Packed meal option', 'Driver parking', 'Local transfer support'],
    tags: ['Aral route', 'Scenic base', 'Transfer support'],
    recommendedTripStyles: ['scenic', 'balanced'],
    recommendedBudgets: ['light', 'comfortable'],
    nearbyKeywords: ['moynaq', 'muynak', 'aral', 'viewpoint'],
  },
  {
    id: 'khorezm-garden-inn',
    slug: 'khorezm-garden-inn',
    name: 'Khorezm Garden Inn',
    city: 'Khojayli',
    region: 'Karakalpakstan',
    location: 'Khojayli highway corridor',
    shortDescription: 'A relaxed stopover hotel for road-based routes with comfortable rooms and parking.',
    description:
      'Khorezm Garden Inn fits road trips and mixed routes that move between cultural stops and regional transfers. It is less about destination luxury and more about giving the traveler a smooth overnight reset with dependable support.',
    priceFrom: 68,
    currency: 'USD',
    rating: 4.3,
    images: [
      'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1522798514-97ceb8c4f1c8?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1000&q=80',
    ],
    amenities: ['Secure parking', '24-hour reception', 'Driver lounge', 'Breakfast'],
    tags: ['Road trip', 'Transit base', 'Parking'],
    recommendedTripStyles: ['balanced', 'family'],
    recommendedBudgets: ['light', 'comfortable'],
    nearbyKeywords: ['khojayli', 'khodjeyli', 'road', 'transfer'],
  },
  {
    id: 'ayim-premium-suites',
    slug: 'ayim-premium-suites',
    name: 'Ayim Premium Suites',
    city: 'Nukus',
    region: 'Karakalpakstan',
    location: 'New Nukus residential quarter',
    shortDescription: 'A premium suite-style stay for travelers who want more space and a quieter finish to the route.',
    description:
      'Ayim Premium Suites is the most comfortable stay in this MVP list for travelers who want a quieter, more premium overnight experience after a long day of route exploration. It works especially well for premium and family-oriented trips.',
    priceFrom: 118,
    currency: 'USD',
    rating: 4.9,
    images: [
      'https://images.unsplash.com/photo-1445019980597-93fa8acb246c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1455587734955-081b22074882?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1100&q=80',
    ],
    amenities: ['Large suites', 'Family setup', 'Private transfer on request', 'Premium breakfast'],
    tags: ['Premium', 'Quiet stay', 'Family comfort'],
    recommendedTripStyles: ['family', 'balanced', 'culture'],
    recommendedBudgets: ['premium', 'comfortable'],
    nearbyKeywords: ['nukus', 'family', 'quiet'],
  },
];
