import type {
  ServiceCatalogEntry,
  ServiceSectionCopy,
  ServiceSectionId,
} from './types';

export const serviceSectionFallbacks: Record<ServiceSectionId, ServiceSectionCopy> = {
  agencies: {
    title: 'Tour agencies',
    description: 'Operator support for visitors who want packaged trips, assistance, and guided regional planning.',
  },
  accommodation: {
    title: 'Stays and hotels',
    description: 'Reliable accommodation options for city stops, regional routes, and overnight travel.',
  },
  transport: {
    title: 'Transport',
    description: 'Practical transfer and vehicle support for moving between cities, attractions, and remote landscapes.',
  },
  food: {
    title: 'Food stops',
    description: 'Useful local dining options that help routes feel realistic, comfortable, and regionally grounded.',
  },
  experiences: {
    title: 'Local experiences',
    description: 'Cultural add-ons and destination activities that expand the platform beyond a simple places catalog.',
  },
  tickets: {
    title: 'Museum tickets',
    description: 'Entry and access support for museum-led travel plans, exhibitions, and heritage visits.',
  },
  tour_support: {
    title: 'Tour support',
    description: 'Practical route help for first-time travelers, family groups, and guests who need structured assistance.',
  },
};

export const serviceCatalog: ServiceCatalogEntry[] = [
  {
    id: 'jipek-joli-hotel',
    kind: 'accommodation',
    title: 'Jipek Joli city stay',
    description: 'A dependable Nukus stay for museum visitors, business guests, and travelers starting wider Karakalpakstan routes.',
    meta: 'Central stay · Nukus',
    tags: ['Hotel', 'City base', 'Breakfast'],
    city: 'Nukus',
    region: 'Karakalpakstan',
    availableCities: ['Nukus'],
    contactLabel: '+998 61 222 14 20',
    contactHref: 'tel:+998612221420',
    availability: 'Daily check-in',
    note: 'Best for museum-led city routes and early departures.',
  },
  {
    id: 'moynaq-guest-house',
    kind: 'accommodation',
    title: 'Moynaq route guest house',
    description: 'A practical overnight option for Aral Sea trips, photography groups, and travelers who want a slower Moynaq visit.',
    meta: 'Regional stay · Moynaq',
    tags: ['Guest house', 'Route stop', 'Small groups'],
    city: 'Moynaq',
    region: 'Northern Karakalpakstan',
    availableCities: ['Moynaq'],
    contactLabel: '+998 90 447 77 05',
    contactHref: 'tel:+998904477705',
    availability: 'Advance booking recommended',
    note: 'Useful when the destination is more than a quick day trip.',
  },
  {
    id: 'regional-transfer-desk',
    kind: 'transport',
    title: 'Regional transfer desk',
    description: 'Intercity transfer coordination for Nukus, Moynaq, and fortress routes with simple point-to-point planning.',
    meta: 'Driver support · Intercity',
    tags: ['Transfer', 'Car', 'Point-to-point'],
    city: 'Nukus',
    region: 'Regional coverage',
    availableCities: ['Nukus', 'Moynaq', 'Ellikqala', 'Qonirat'],
    contactLabel: 'Call dispatcher',
    contactHref: 'tel:+998911550011',
    availability: '06:00-22:00',
    note: 'Useful for independent travelers who want a clear transport fallback.',
  },
  {
    id: 'fortress-road-driver',
    kind: 'transport',
    title: 'Fortress road driver service',
    description: 'Vehicle support for Ellikqala and desert-route travelers who need a comfortable one-day fortress loop.',
    meta: 'Route transfer · Ellikqala',
    tags: ['Road trip', 'Day route', 'Driver'],
    city: 'Ellikqala',
    region: 'Southern fortress zone',
    availableCities: ['Ellikqala', 'Nukus'],
    contactLabel: 'Telegram booking',
    contactHref: 'https://t.me/baramiz_route_support',
    availability: 'Daily on request',
    note: 'Designed for route continuity rather than mass transport.',
  },
  {
    id: 'nukus-market-lunch',
    kind: 'food',
    title: 'Nukus market lunch stop',
    description: 'A practical city food stop for travelers mixing museums, city walks, and short local-life moments.',
    meta: 'Food stop · Nukus',
    tags: ['Local cuisine', 'Lunch', 'Market'],
    city: 'Nukus',
    region: 'Karakalpakstan',
    availableCities: ['Nukus'],
    contactLabel: 'Walk-in friendly',
    availability: '11:00-20:00',
    note: 'Works well between museum visits without breaking route rhythm.',
  },
  {
    id: 'moynaq-seafood-table',
    kind: 'food',
    title: 'Moynaq local table',
    description: 'A simple local dining option that helps Aral Sea visits feel complete and region-specific.',
    meta: 'Food stop · Moynaq',
    tags: ['Regional dishes', 'Tea', 'Quick stop'],
    city: 'Moynaq',
    region: 'Northern Karakalpakstan',
    availableCities: ['Moynaq'],
    contactLabel: 'Walk-in friendly',
    availability: '12:00-21:00',
    note: 'Best used as a practical pause before returning to Nukus.',
  },
  {
    id: 'savitsky-entry-desk',
    kind: 'tickets',
    title: 'Savitsky Museum entry support',
    description: 'Museum ticket and visit coordination for travelers prioritizing art, collections, and guided interpretation.',
    meta: 'Museum access · Nukus',
    tags: ['Tickets', 'Museum', 'Art'],
    city: 'Nukus',
    region: 'Karakalpakstan',
    availableCities: ['Nukus'],
    contactLabel: 'Museum desk',
    availability: 'During museum hours',
    note: 'Useful for time-sensitive cultural itineraries.',
  },
  {
    id: 'heritage-pass-support',
    kind: 'tickets',
    title: 'Heritage route access support',
    description: 'Coordination for travelers combining multiple heritage points into one more structured cultural trip.',
    meta: 'Access help · Regional',
    tags: ['Heritage', 'Entry support', 'Route'],
    city: 'Nukus',
    region: 'Regional coverage',
    availableCities: ['Nukus', 'Ellikqala'],
    contactLabel: 'Request planning help',
    contactHref: 'mailto:hello@baramiz.uz',
    availability: 'Response within one working day',
    note: 'Especially useful for curated educational or partner visits.',
  },
  {
    id: 'craft-workshop-visit',
    kind: 'experiences',
    title: 'Craft and culture workshop visit',
    description: 'A lighter cultural add-on for travelers who want something hands-on beyond a standard sightseeing route.',
    meta: 'Local experience · Nukus',
    tags: ['Workshop', 'Culture', 'Small groups'],
    city: 'Nukus',
    region: 'Karakalpakstan',
    availableCities: ['Nukus'],
    contactLabel: 'Reserve via Telegram',
    contactHref: 'https://t.me/baramiz_experience',
    availability: 'Selected time slots',
    note: 'Best for travelers who want local interaction, not only landmarks.',
  },
  {
    id: 'aral-story-session',
    kind: 'experiences',
    title: 'Aral Sea story session',
    description: 'A contextual experience that turns a Moynaq visit into a clearer environmental and cultural narrative.',
    meta: 'Story-led experience · Moynaq',
    tags: ['Storytelling', 'History', 'Visitors'],
    city: 'Moynaq',
    region: 'Northern Karakalpakstan',
    availableCities: ['Moynaq'],
    contactLabel: 'Reserve by phone',
    contactHref: 'tel:+998912001414',
    availability: 'By prior request',
    note: 'Works well for judges, delegations, and guided cultural visits.',
  },
  {
    id: 'city-tour-agency',
    kind: 'agencies',
    title: 'City and museum route agency',
    description: 'A light agency profile for visitors who want a packaged day around Nukus museums, food, and logistics.',
    meta: 'Agency support · Nukus',
    tags: ['Package route', 'Museum day', 'Assistance'],
    city: 'Nukus',
    region: 'Karakalpakstan',
    availableCities: ['Nukus'],
    contactLabel: 'Call agency desk',
    contactHref: 'tel:+998973334455',
    availability: 'Daily consultation',
    note: 'Best for assisted travelers and official guests.',
  },
  {
    id: 'regional-tour-operator',
    kind: 'agencies',
    title: 'Regional tour operator support',
    description: 'Support for travelers combining Nukus, Moynaq, fortress routes, and overnight logistics in one itinerary.',
    meta: 'Agency support · Regional',
    tags: ['Multi-stop', 'Operator', 'Route help'],
    city: 'Nukus',
    region: 'Regional coverage',
    availableCities: ['Nukus', 'Moynaq', 'Ellikqala'],
    contactLabel: 'Send inquiry',
    contactHref: 'mailto:routes@baramiz.uz',
    availability: 'Response within one working day',
    note: 'Useful for visitors who need one operator to coordinate the full route.',
  },
  {
    id: 'smart-route-concierge',
    kind: 'tour_support',
    title: 'Smart route concierge',
    description: 'Human follow-up for travelers who want help turning a generated route into a practical day plan.',
    meta: 'Planning support · Platform',
    tags: ['Concierge', 'Route review', 'Travel help'],
    city: 'Nukus',
    region: 'Platform support',
    availableCities: ['Nukus', 'Moynaq', 'Ellikqala', 'Qonirat'],
    contactLabel: 'Message support',
    contactHref: 'mailto:support@baramiz.uz',
    availability: 'Working hours support',
    note: 'Bridges the gap between digital planning and real travel execution.',
  },
  {
    id: 'family-trip-assist',
    kind: 'tour_support',
    title: 'Family and guest trip assist',
    description: 'Support for family groups, visiting delegations, and travelers who want a calmer, more guided planning flow.',
    meta: 'Planning support · Assisted travel',
    tags: ['Families', 'Guests', 'Comfort'],
    city: 'Nukus',
    region: 'Regional coverage',
    availableCities: ['Nukus', 'Moynaq'],
    contactLabel: 'Call planning line',
    contactHref: 'tel:+998903210099',
    availability: 'Daily support',
    note: 'Useful when the traveler needs support, not only recommendations.',
  },
];

export const serviceSectionOrder: ServiceSectionId[] = [
  'accommodation',
  'transport',
  'food',
  'experiences',
  'tickets',
  'tour_support',
  'agencies',
];

